baseURL = "https://elhadiq.github.io/"
languageCode = "en-us"  # Update to "en-gb" if you prefer, or another language!
theme = "anatole"
enableEmoji = true

[params]
title = """Zouhair El Hadiq	"""
author = "Zouhair El Hadiq"
description = "teaching and courses"
profilePicture = "images/profile_pic.png"
mainSections = ["post"]
postSectionName = "blog"
copyright = "2020-{{ YEAR }}"
displayMode = "dark"
doNotLoadAnimations = true
contentratio = 0.8
gtagId = "G-D4752FG3GR"
#readMore = true
#fullPostContent = true
enableMediumZoom = false

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/elhadiq"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/zelahadiq"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:elhaidq.pro@gmail.com"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/zelhadiq/"

[[params.socialIcons]]
icon = "fas fa-calendar"
title = "Calendar"
url = "https://calendly.com/elhadiq"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/*"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
[languages]
  [languages.en]
    contentDir = "content/english"
    languageName = "EN"
    weight = 1
## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

